server:
  port: 9022
spring:
  datasource:
    url: jdbc:mysql://mall_db:3306/tower?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: PgFrPRbs5uY
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: garrupaCP
      connection-timeout: 30000
      minimum-idle: 30
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    database: 0
    host: mall_redis
    password: PDY1k6wFxN
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 20000ms
  application:
    name: julia-pro
# 日志配置
logging:
  config: classpath:logback-spring-pro.xml
swagger:
  enabled: false
file:
  uploadurl: "/home/upload/images/julia/"
sign:
  salt: ID6IxM1YzwDMN

deposit:
  url: http://39.99.38.129/deposit/

alipay:
  url: https://openapi.alipay.com/gateway.do
  appId: 2021005186683061
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCSPki6dpkI3Z4TenErCOKsEfCjR1ffMzf2QthiTMKFZ4/TRGa+jQEajl80yhBP3PpDc2r80PUTLoLWRwQJ4fiBRR42WMm2zbwBx47UuQd+PShY5JGPVAf1rnBTmU0qHA9ygGjYCtGANxf5CksAA/tppg/tyEKJASY/IpYaCHoxcsLNI+MYdDIkak7BL6q4vaN5J9qW6mf8rlqR93wt67qNSVdodZkQQObvSVR/hlN9BiuKLS49XmL9nDrXhSsyQtEgtSJyLmuocVBzpnvjK7NAmgn7UQhmnYg5Kc9vd/EyUvSYJLJYx2kw0BRSgHJ+3niTiK86Jmfr8qX8O1MbRKBPAgMBAAECggEABMZ74XrV7HAwJTquT1Vu8Wd0kCBYQjWN8kCkiDExeOG01JU7NaWtD4zulu6yMalpkqJGMBMyrXmrVAvlmd0DHFWBcwzbKVj2dqhphZC1Ke4dTynHhwKbb+5ORKyQ1HsuFfMTeVqBFMq3wa4QXOPEZeLCSmVrpsWe1hjvBdKZCtxD1FuovYwIcEDpWiFS7TyYHeWa1vRvXKBe68OZ+M5pHCSAChj6MG9NZaboVUrROPXL5zLQeTSCae2FlLtQT9tx0ID++mfghIjwodO0EL8AXMWFAL/VZC5dFCkKoYeLosdMQNxamATujPqhZLAwnRzRs4PquHOVbUtGhbOSibO9wQKBgQDGE2D7rxINdTRUiFI9ungwsAbNZMwMJP9a3sg5j9cV1SlysGZCmUIEIqROpI5hw19eVpRzwCKpuLJkTP7T8RnpI/mroVNmgQyUa8SiwlIjli2/YBLWLkme+/h8hC+onAn7yLgLWC1jLPT6nraeDa0iuaEZWxDGXIP0BSZG0ar3ZwKBgQC9Ao4jFJh0j3fRqfNPf4Zc9HeSobJrBxZo9HAhEso++Ie1CUi5WKvir2tdZdYl6KmRv3kvuHNGnXHKyZSSNbRt+YZpfUESBjPJk5DBJjmbp84sMG+0Xx2weTsJ4Pkw3MC2wfQiaXNviTelgdWjABgd032RhVQXKtzF8gvtgr+G2QKBgBth6nJgzXoWzdkxz0zBToRMkWQrnxm+s554Ve2/ONjH0ycLw9dJIJs5vsUwco6JV9HO3k7yLNiRs/exvTjHh/F3C7jyYHk3Nen+y/xEKN7KkCB4w6HgXEUiSEPOclg42hh4sxi+Y+fl+yf6cPyAn4LBbsf2kucZOxSs8ZGwwpXZAoGBAKHjf2TSriYgAAun2ku8OZSCm6wPLSd4wZwRyby6QFohOvM3yX9fUJHvmDE+GWcM2biJXL4f6TSRhDah48w7jZgoghT2gHZ0s4SzDOgy2mLVHsVAk1zVnzNZEtVKSYWtfq7Kf1W+Jm5hBDWReC+N1Bov3Dx5C2ZwgvpUcBz1wSA5AoGBAKFNwkYci9mfHJdXDM/S/dQ55JFxsiVUtJ7cFLfL7LeAoAdo1JPYk0dDwH7wWhaPAlveeSbkvWPoAhH+uYUz8yXK+oyoxI1U40YcAxkktl5dlmQvBLpEuSnaWoiVkqOCthu7wxTciW9NAIGM40w6r7ADgLGEJhV7c4qUCA4e5iQV
  notifyUrl: https://haimeiplay.cn/kl/api/callback
  appCertPath: /home/cert/appCertPublicKey_2021005186683061.crt
  alipayCertPath: /home/cert/alipayCertPublicKey_RSA2.crt
  alipayRootCertPath: /home/cert/alipayRootCert.crt