server:
  port: 9022
spring:
  datasource:
    url: jdbc:mysql://47.98.112.27:3306/tower?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: PgFrPRbs5uY
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: garrupaCP
      connection-timeout: 30000
      minimum-idle: 30
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 60000
  redis:
    database: 0
    host: 47.98.112.27
    password: PDY1k6wFxN
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 20000ms
  application:
    name: julia-dev
# 日志配置
#logging:
#  config: classpath:logback-spring-dev.xml
swagger:
  enabled: true
file:
  uploadurl: "/Users/chenchengwei/project/chowel_master/resources/upload"
#sign:
#  salt: ID6IxM1YzwDMN

deposit:
  url: http://39.99.38.129/deposit/

alipay:
  url: https://openapi.alipay.com/gateway.do
  appId: 2021005140622735
  appCertPath: /Users/chenchengwei/project/chowel_master/cert/haoyuxin/appCertPublicKey_2021005140622735.crt
  alipayCertPath: /Users/chenchengwei/project/chowel_master/cert/haoyuxin/alipayCertPublicKey_RSA2.crt
  alipayRootCertPath: /Users/chenchengwei/project/chowel_master/cert/haoyuxin/alipayRootCert.crt
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCoh+ulJDVlQfv/5lyz7U8+GpGOVDtWNDzBZVGHaYp2S0gxfKqLgaw0BqEAJfuVA/czBXT5unC2tuB2Q6DU4wUiwYAt01moMDf9en1fDATsqFRbp/YT6rCDTCyMQLy5nzQzhgayWsqV8j/qITqwjGlRXSzaQJEMbgIK9OzUgmIASmUMpKw7UjjSGvAMDG3BFzKzA4db7M6fbzZY6+dEgTKBnqj6LsZWbNHcj99lTbw2Q8NTrzgfucMMCxuTaZO9X7iGRVIJbcwxFBoy41+/mxA8F33SxAH+zcb8Dn4akZEafaNV/E/WNRAFEtWHHg+3nTTaLERr7LTx04akodJuzTsxAgMBAAECggEAJb67YjMn2lPa8sdPP+UIeGpO60emOnpcmRvuFJvorPHTa3H2aGRUgxpw+K2JGSjYNo8kUcIV+HYg85vV65gk0FHyOVE6pVaXU6gZaC4y9CYHLrgBfxhzDBUFbSwamKA1esyrt0pqUQb+lZt3n47zD4wEvaT0V4pT3sxYNog1Fsc1DWIP4zUw5v48CVKpritKoLMeenlgaDrZwVe68QmfDC53YtOUr4P4dbQbstj1cAXK/wKuMAAUW9n681uHhsSqN7LPcxyXpkXeNYnTjh7omBAtlloJQyWyM8bMvOKhNhCly4fD6hPNxXOIDzV4BNUlZq7zngtqM/g5XxEbUoH5mQKBgQDpGXFvamqb8DnmTFDiHMH7ZzZP4PdHBjWLB77Aefm0iweV2hyR9p4dnkPFdy5poNbkjch14vyNanbS2Z3PI/NwMYkunUfgIV75Fue2esl0orRhvG4apo+rC6fRBX9d+TsET7xfXZY73qEY3Y/6/TxqXoa1d0AMXeroZ/6vukuzfwKBgQC5Fo0bTpnkvIAeF8w8jLNiRWNCVfOhc/vtlvwIU1ywr3Bl4McufrOZ4M2hDAE/zMvw7sEHvthFktF0D5j/wRSkNEbPScDs0EzbtEcgiCIactQ0JYz9Q9Hhlye0cqu/zCZ5R2HjrBOU9Ox+6HSqVQ9fOTCpw0NqLzJM+U5vWQ6pTwKBgQCUabW2yZutQ6upvQd2n/bGWfXTsBnhJ8vphHnoVQEu+aJPv/qW2N3dX8oorPRpHpYUGU37+RTx+UpEf3ghzfMOiQueGVgNFVJB6FqJ7e3cjEerPu0fnNM2hYpI5GYu8COqYBZA5fZkkiAiE9e7Z4cS9rJwUcf+18FcTfJz8nqGgwKBgC/bDdb+prnGp1Wgj5UkSAljqXtwX9Lh+0R+ImJAs5mXcvdUfAughO2He4NlaDlHyX9dLBnFlYO/p1pb4hJWqPCf96MHDdPtM8ImxbE6oZ63C/kDsIWXcH/kpkZ408F+loALHdtRFasQ/Mj/b5LO9W+IiPWL4DVnSJkwaMBPhYPvAoGBAIS6d5ZMw3pDRJVyLg08LXgvx65XG1Y2y7O/+5C2CCWnqsshbqSxQ5FaTJ+e26zTtL3M7WdoX7YgvdzxWARDGZVZi90/rChC55gyIL94Wrr1MCIM5cSnlm6WnlNuw5Lu6yX6JMZXQx+KaNOFidFQFq4LbYVCNPAoYzvLDQb/yyv0
  notifyUrl: https://game.haoyuxin.top/kl/api/callback
