server:
  port: 9022
spring:
  datasource:
    url: jdbc:mysql://mall_db:3306/tower?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: PgFrPRbs5uY
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: garrupaCP
      connection-timeout: 30000
      minimum-idle: 30
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    database: 0
    host: mall_redis
    password: PDY1k6wFxN
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 20000ms
  application:
    name: julia-pro
# 日志配置
logging:
  config: classpath:logback-spring-pro.xml
swagger:
  enabled: false
file:
  uploadurl: "/home/upload/images/julia/"
sign:
  salt: ID6IxM1YzwDMN

deposit:
  url: http://39.99.38.129/deposit/

alipay:
  url: https://openapi.alipay.com/gateway.do
  appId: 2021005184672130
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCJSr5gSFBtjF8MrkHaS1J8zvvwYdUYgv9oDAMeWuOkBmqPdpQMT5Dd/tb5A2diA9fnGJM7L53b2DRCz/DTTAh5tMgUEzKHwDlm1Jd/nKQNFWOMrCetXOn4A+3mcRnsgaE75upcgLUuFLJlYVArOxFqUr+nQMJjJOosH4D88gi6JwBD9mI7KDvAMTa2zdSVuel42h2w6cDD89OpiwvQDrf5Ck1liZkNKoUSzNwqToA9oKp41e+QSiX2fBQUAPFa6tnw8knt5MVtS0pKCzgDHbqafCpBVl/LJvhsr+UEnrk+G4D/GZ4AIey1yfS2KhuF/c8HJnslg4hgR/NPVdDr7f/XAgMBAAECggEAK+M+1FyJiVt0DwOtfXDSn58zHnbHvhwyNTqRzKRVXNvIOLA5R24v6ydJ5TRXWhfMbs2GU0c3eU219x2t6H3Hv9AwnWo9nvOt5ddTzrFuJ9iMiC2ISX0INgZbiGzjUp1lw1Zf2M40HNT06j+fdxJc0NY++eJTwYnNaelwPGvKqmbRE+8Tcl8GrMs6aPtet5p6d0t4Lj4qLKNT6dyrux7de+Muu/X04QTVJLEDNmoYuD2Q6FOyeyfrCY/lBW2giDF2p+wIt2c2+/k3U+Mce0LqscvsBEurAoaL1pxOFRtWuMR3dOM2akOmrcGrTA20ETIAzLEw6XjosllUJnNuWE4s8QKBgQDKRvRuuNKodIcBNRphQdFiyFWh1PP6cVY0NcN8sc5niYPhBntw5VX7d2T7XYekPmalprOVHw/X5mKEKs3/N1d9KEpUCivyHT24i0u4cxgzxMSFDBRID4Nr4snPipE9cwqWvgPfeK0A66JL+jzR1CppzzjXP4/+hJGc1NBeOlnpywKBgQCtwV/OGXwN4m5eBjAxCXO7CnqRZMQiOoAX+Lin+a7YVR9nnbu2n7UuHNulww73JQ4QL7RLQVJ5DsTM0lDoomPwrC0SnManPAKtkVv0ArKIK5bG6C5Udjy0YoBJUcJ1HrsuCChy3zeEtm2j00EKEY2SpHAsrQ8nFZV2CD+85OTwpQKBgB6BrQO15C97w5CvDZd1cbrQM/oAP/uZdELTiPQZbOO4nacmbx+LtvgB/bzbUkW3E4wQJC1tTdpl6J2+Rusi0ZMSrIMYNaCCQHjAqV7cHN5R4sGeHMDxdgSjY4RlhZoa65HofnUJoi3tW8DRsLKEqRDkK9Jqx7C/Fabtga90ZXMZAoGAB2m0mKplrIH4i3JgI/dvRI+R4xoVdBBi3qLx3di9KOWYzWbhV01BAZKhnFTSEqE2FGK0onFK/3ct1j8yzHoBIYd29NBTeVcKFjWZYrOqwjx51kqZj2jr9hYtuvMOBMkm2zPl5eC4EaVm0BJ3N+K/033Ie192wggdtEdt0LVDPzECgYEAjg2OaU1QzLejgwR9qO6Hww7bFZVVuBuk6h0W5gKF7uNR3HrJB3JrTGh1z6MPo7ZGd0u2DhKp/gchqWFO4XOYTwdZiWbav3nCbQOAW3j05u0bjptVJR1TZbz7YbW73wITwzmbb1cjSG4vIaTsSCrlV4I1Z1NdU3D639VQkMAOz1s=
  notifyUrl: https://game.abskj1.cn/kl/api/callback
  appCertPath: /home/cert/appCertPublicKey_2021005184672130.crt
  alipayCertPath: /home/cert/alipayCertPublicKey_RSA2.crt
  alipayRootCertPath: /home/cert/alipayRootCert.crt