server:
  port: 9022
spring:
  datasource:
    url: jdbc:mysql://mall_db:3306/tower?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: PgFrPRbs5uY
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: garrupaCP
      connection-timeout: 30000
      minimum-idle: 30
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    database: 0
    host: mall_redis
    password: PDY1k6wFxN
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 20000ms
  application:
    name: julia-pro
# 日志配置
logging:
  config: classpath:logback-spring-pro.xml
swagger:
  enabled: false
file:
  uploadurl: "/home/upload/images/julia/"
sign:
  salt: ID6IxM1YzwDMN

deposit:
  url: http://39.99.38.129/deposit/

alipay:
  url: https://openapi.alipay.com/gateway.do
  appId: 2021005150647655
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD7Lb0hl/lJOSL4UNIgs/oD698P0IKFb0x+doEiHv4KmeCtukzCe8STFBPTC5bBA7Ni5a40eTJgTA9xtNGRuPu9dTbM1/WDX20NlzD+1jUrAiEVQIxPpKNDMjkDTyPiuvWWJZVHN/NojgPY1pMsSzUaRUtynINYf0HmP3MBOKjp+ihWPjHpFzVmWzOcregvPmk669qc+F4BSyr9rJ20roKK66TZ14yh3yDqVwbZ0D0C4ahCkg7wyLf6z0FvLpjlh29Z3sTxknlB2dGyabxesqD/jb/h/49zZuEEKZGTFn24lLjVvEi7m7cRFdeIK4JxgHFsbuXNBbkwi4EjUvAnxvM9AgMBAAECggEBAN39SZdkGkTVw4tU2rFefwtyLl1qucA2YpOuJmjCnWE/KCxCZ87G1i/q4a53IpCJtcQlG/ZyWsxyzH+BAGra41pJOtqFzw2Bi/8j7YB8Ttco9ZYzyw4kgspDm9HJ4vxioeRGaQ1dbLmuMcY1tjLCcTc7oPe1Tfwr1FErKHge3GKUHVHfeDkSjRsQF4c6s5LUHU4oXo1eN+8ihnyM61/lBTVAj0sPP/kdNmCZkOCKbP0vainzzbBm5SVVDFzdEomTo3e76MasMBvsnbm2r2qF119w9dn0aUIfG5KQwqS9GsiQebA50js/NvVLyi7sK/vBr9ava+et9XKB3diWXqPWuaECgYEA/kQJ20BkvE8apDUHMjaO4gXaNILekEkMTfvukXO93XR69gm9tHj6XroPtrTAY5l9sbVtayiuPA1M9kEIIwTVliahSkL9fGOPcf1KTPqipDKbqzKqRhndeNVMj4bPowyzJSF5TB4XolkfyUaxIkAbOSkSSiG/1ZBv7HJS4VohyckCgYEA/ORPXqJkHiaEcQRqozmDLv7W2nSvldakm+y6kd6vkk6Bq5Mpn3p7hmlUa40zQQkyJVVcXcngrMiLknxKZWye7VFHq0eXdr1gnIpVMDVuqi8l4lbUY/xRHPfW7ysxyXv13OAfI9vHwZankQfNZL3C4uEpQ9IEh0V4IDAC7gDBF9UCgYBa9dIk2ltvNklMlx/U6cmhuABAqtSd/1PkjgzhgetZTvMyE3gHGQRQYPWAIhd1ShK6QTI8lJgIKaXvroIPrQoPphArNd3i4ucNG1S6Rytp3CTuULizTUt6j6vM6KhdJwzrapcvENDZplKFucFihFZ402WUmZA8AWjYyGk37vuJaQKBgQDOUQl7wGqDupLUjXDeZ35h6eCpawcQ7INw/kob1ZxRdaEOtEoB5PA/8VDBSfoltfXmRWTM03VsIVTVFnevlVV3cZdR4l9srQXT0Hu9j+oQB9UVehde1yvpwTzl9Mxyf6JPJ73gCF9Izbs5dC8aYEJNzLpYrU+qeH+PavwI5i6iXQKBgCVzSroSCm3Mp18/9ntC1MDokCpgjDv6T3bU+Jx/u7yoKbE9rQ0sCbimkgRMq0fwOvCnlCGVp3u5sUyxsIiiOXNffWB8bf1sd5lHKWs5cS6a+UzV5jtZxnZo8l673O0nsJ8pRQavjvh7ff2RMAO31iWalbzF9EkFo2nTQJamPn+C
  notifyUrl: https://game.jiasuo.top/kl/api/callback
  appCertPath: /home/cert/appCertPublicKey_2021005150647655.crt
  alipayCertPath: /home/cert/alipayCertPublicKey_RSA2.crt
  alipayRootCertPath: /home/cert/alipayRootCert.crt