server:
  port: 9022
spring:
  datasource:
    url: jdbc:mysql://39.99.38.129:3306/tower?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: PgFrPRbs5uY
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: garrupaCP
      connection-timeout: 30000
      minimum-idle: 30
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 60000
  redis:
    database: 0
    host: 39.99.38.129
    password: PDY1k6wFxN
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 20000ms
  application:
    name: julia-dev
# 日志配置
#logging:
#  config: classpath:logback-spring-dev.xml
swagger:
  enabled: true
file:
  uploadurl: "/Users/chenchengwei/project/chowel_master/resources/upload"
sign:
  salt: ID6IxM1YzwDMN

deposit:
  url: http://39.99.38.129/deposit/

alipay:
  url: https://openapi.alipay.com/gateway.do
  appId: 2021005120673598
#  appCertPath: /Users/chenchengwei/project/chowel_master/cert/minda/appCertPublicKey_2021005120673598.crt
#  alipayCertPath: /Users/chenchengwei/project/chowel_master/cert/minda/alipayCertPublicKey_RSA2.crt
#  alipayRootCertPath: /Users/chenchengwei/project/chowel_master/cert/minda/alipayRootCert.crt
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRpvyjBdnaFETILklSXOwsavwj9P4pkE62IdnsHkg1SpCQzfyG6AHWx6EK1dsAtW8zCmpxz0vbaq5KX9j5wF3lz/TlWkVJI2G2ZQ+Bs1yAPi7YA1jR5Y2EcTwYSBRKNuUGpI/f6sghrk8QVGJ6DOFSzasCCSLNyz4em/RrkLH31jbmi0uFS487YuXXtadBKS9pp3PdklfVgHeA23ODE+omkN1eOhvi3b1/f5EPa5OBmIDrPSxfFtxV+5oAbw7mAgBeWxH2QN49zcGCdz5tSGj/0KMdhk1kT+z/umM86RrjKTYbg4AHvqGMrQYaPtEcP14r/JemwLIttHMEEuJiEzc7AgMBAAECggEBALHLJVCzM47HxZTl+/RHLVp12CI+MBTbdoTqrD6bZ60Z8QN8TH2z32tfnGjt923gb88fNCoUHEaVb/1Oz1juFDNCanLeXQerY8AkcEQT8YwoL92s6PQH8j2xMb990QcnCo7Zm9HO763wfshgZ6sNpUBtfmqZiNRxWdrncx6NdP+xNkVVHCL71Rs2tfF0XUnTapUqhwdgAkTM0PdY7WsXHTxo20wNsVNBNQaVAcx6PIcipVY/qL4+n9YsZQvEQ9kjotnYo0EDCGFNCL0qNqtmAz2xbsI1t6DyZaP7DmDwbw75mGx6A0ijNdAD+d5/Dgr8E5MbkP/pIDBxa1ijiSqtKtECgYEA/AQn08Nu/Lmds+gChw8mWU9SLWSKvCVwrkHFe+h2oIOFjn2eGFXMwV4OLQOGKIKikr4zabWVj6gGyz4ZXn/6zz1iaDJf8W+WeR5U+XMngIJW49NGF8enyY8KHe3wt/c/ir9tE4aOHxiCPUJuQz/97nKvPfJAi9Aw9/WpRxzuJi0CgYEA1PdlOHfu54D4PCboUGSjdbGVmo2+TGmQdtw6tiHZI2h7NgS56RuBD2dYdeuwm8l8uOWvN7ICy9CCripTetmucNyZpIQJRLUiNHRxxaykFC9xySYZgmcF1XTeIxNfTlW2eGWl3oy2NuqqZxuYJ3KB36zZ4hq/QOYM8oCfTkg4XAcCgYEAnqxDIzqmc6qul2pZxQ2N2KdvlzL5gtKT6rNwkr5filqkyX1f//RtkcYVaNQSMQlnMLtehY0V2LgzZt33fR9ZHAiLIA2viMT4WdP2LoUJdwkZiiIovKoxg19zQDri2AFtWX+DPsr2Sq/UuJtN7zuoNuywV3FioGT5n/VlmmelrhUCgYBiGC5Ei2G8urgcpOM/HIv6SzkYvo9YDQvg4+IbQI4O9DJEmHq1t9iDqtuhPVXU/EL5u7owkksdbEa1SIO5Q4lJLSOMFtFaF4DQ3o4FOlc9gPkNaQI5AZE7WCB10ZeFso9g95kmYHQR6Zdh9ODp0qGl0K1vq1hK4Ww3Sy2V1kg3gwKBgHZNq2GkfKb++ULkq0VL/UO7AQAoAQcMw1GdOQ0Jf8yQhx2wYisDcbSPLM7pzOtLqOaLqGfiCSdatFHVC0RdfWDZHNNhE+VGm40dglr1gm1YTXTn/211WALtjWSWBZzW6zngduJFbtLJfq59gaqpNAH5f48Xjb+KuJ3hMzoVPsk2
  notifyUrl: https://dev.tianchenhulian.com/flow/flows/app/pay/aliPayNotify
  appCertPath: /home/cert/appCertPublicKey_2021005120673598.crt
  alipayCertPath: /home/cert/alipayCertPublicKey_RSA2.crt
  alipayRootCertPath: /home/cert/alipayRootCert.crt
