server:
  port: 9022
spring:
  datasource:
    url: jdbc:mysql://8.130.124.186:3306/tower?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: PgFrPRbs5uY
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: garrupaCP
      connection-timeout: 30000
      minimum-idle: 30
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 60000
  redis:
    database: 0
    host: 8.130.124.186
    password: PDY1k6wFxN
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 20000ms
  application:
    name: julia-dev
# 日志配置
#logging:
#  config: classpath:logback-spring-dev.xml
swagger:
  enabled: true
file:
  uploadurl: "/Users/chenchengwei/project/chowel_master/resources/upload"
sign:
  salt: ID6IxM1YzwDMN

deposit:
  url: http://39.99.38.129/deposit/

alipay:
  url: https://openapi.alipay.com/gateway.do
  appId: 2021005134605312
  appCertPath: /Users/chenchengwei/project/chowel_master/cert/LinSheng/appCertPublicKey_2021005134605312.crt
  alipayCertPath: /Users/chenchengwei/project/chowel_master/cert/LinSheng/alipayCertPublicKey_RSA2.crt
  alipayRootCertPath: /Users/chenchengwei/project/chowel_master/cert/LinSheng/alipayRootCert.crt
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCBpqnNfWmk4hXTLxalVwXSYq2bGf7Fhr3EA/CcLTvV9YLyCo4dmREGbZfBq4H+MiNombkCqfx0/G0qn4QBUH4mKWGIOHOxfSVTdsmkImYa+SD2OyTMiwXbsIkAEb6+LIbVWhN2Xb26Qzu708b7fVsOxig7GfKSKIkSJGWOP1Nc+8DmbFdLxwlkiyXORLOVDUh0qBpsCXQgFF/K2N46BZ6C43qsHDYI23yhJKvmQVufK4SridHhDL+SEJe3CEIopMVugSzvoGVwfj1i0+WzV9rioh+QVkr+1r4JQDtlsVu55pwAVr2rj1xLPlm9UmcG7EqIwGLjl/tuLG9ugGPWDI+9AgMBAAECggEAMkvFc8JDSYOrk9Ggp2OrDoLZdmIPQ/GRjIk6vluN6uLjeaI+n5zRzfyV8rvmIgaxVdLMwwvOtFN4xiA7xYbEaWmEPKQpvaEe6dIbR2FQ2wXqk5s+G1uTWjaR70TzCjOb2wimpDSZdbi/Y440kzt+J60XzlWylKDFDBSykQxf+qHaplHESgZTRBI48OgXmeU7hgGcULTcXskzgWm2lW5QsObjOT//XRs9PnWEKz32xUo+kQppx8BTcc8hoyPgHJErRKoU6MzwDEKSuuK9TaqEWvSZt1biXvPy3ELD6+Vt3xODW5+lh4q2KZY8NfIlbHKFjWuXv30zb7e+T7d3NUc+AQKBgQD8t6xbl5TOdugr6nkxlC6QYLlzXIlDgYbEC4IJoR06NE19pK8GWnnCVRZ6RMJVFjvcuatnVwRSNqKurMdEGZAMihe9sblEJMVc13GJE3aBwBtSDW4ATsY4yTPhWoTy2ZCgs6zio+BADSjS58yQOaa64wNNSKcuqE0ocYVYPTcdxQKBgQCDVcYo2z0NOum7gnm9l9wWNnAo49QoCz6kgF/Fn3a/0vCmg0ksKn0sQ30rqYe0f5Tp4qJgC59u8lx52llyskUjAN/Aknc7drYmAeeD7kLMRY7PpYobbKhtPjgr0bmaSn3pbNrSGMJOJIEWlJzskMa/0bWfFF2t3w2yNfRewuYBmQKBgQCcM/s48cxsgVqoKlmWp3zQiLiX8Y52R01BR8usoAUswL9U9cGpL6sqzuUB1hY3+XIu0CR9z29AUbzkMq9IDHTZC1H5UiytTf0fkZr/myQYtuEsKljfn9EtsE987zJV2NxoOCaYP6qQbJHbKqNqUfgYc9DKqCmN0UE/yksda1jx8QKBgEKh5/GembD2rNMndWCNhWn3oJv+Swst+VA4mV6IcxULjnDMtvkjbXJho0Xdsy4OdJzdEQitnOwLJoPkFfGtJIqHzP3E0Z1nsy5BVRaIcXd16ujK0fDsBd+264S/2OzA0nT1d2eUjDBdMOkl6R/UrCFx4jWdfZHTUv2RhjP1qgAxAoGBAM1wK3H+P236P7ZT72vjNrQDDsvbiZL4SIjiIPqExmx8tHvE0jhRKrgvWbSfnixg81wCn9xIae+E+DOydpsy10H4MlbAEEZx/qpN1Z2HhGTB1zN7jfqP2hBmXZg0iHPNmvb4bbS6JtXswu2AFaH7sffzGXRqqSzpQk5/h2MLTmnV
  notifyUrl: https://rpsls.cn/kl/api/callback
#  appCertPath: /home/cert/appCertPublicKey_2021005134605312.crt
#  alipayCertPath: /home/cert/alipayCertPublicKey_RSA2.crt
#  alipayRootCertPath: /home/cert/alipayRootCert.crt
